return {
    Thaler = {
        Icon = "rbxassetid://16066723093",
        LayoutOrder = 1,
        Max = 10000000,
        SellPrice = nil,
        BuyPrice = nil,
    };
    Leather = {
        Icon = "rbxassetid://121389679771359",
        LayoutOrder = 2,
        Max = 150,
        SellPrice = 4,
        BuyPrice = 7,
    };
    Wood = {
        Icon = "rbxassetid://75868542804246",
        LayoutOrder = 3,
        Max = 150,
        SellPrice = 2,
        BuyPrice = 5,
    };
    Stone = {
        Icon = "rbxassetid://82341448888479",
        LayoutOrder = 4,
        Max = 150,
        SellPrice = 2,
        BuyPrice = 5,
    };
    Iron = {
        Icon = "rbxassetid://73163553126095",
        LayoutOrder = 5,
        Max = 150,
        SellPrice = 4,
        BuyPrice = 7,
    };
}