return {
    ["Wooden Axe"] = {
        Damage = 1,
        Durability = 100,
        SellValue = nil,
        Cost = {
            Wood = 5,
        },
    };
    ["Wooden Pickaxe"] = {
        Damage = 1,
        Durability = 100,
        SellValue = nil,
        Cost = {
            Wood = 5,
        },
    };
    ["Stone Axe"] = {
        Damage = 2,
        Durability = 150,
        SellValue = 30,
        Cost = {
            Wood = 5,
            Stone = 5,
        },
    };
    ["Stone Pickaxe"] = {
        Damage = 2,
        Durability = 150,
        SellValue = 30,
        Cost = {
            Wood = 5,
            Stone = 5,
        },
    };
    ["Iron Axe"] = {
        Damage = 4,
        Durability = 300,
        SellValue = 75,
        Cost = {
            Wood = 5,
            Iron = 5,
        },
    };
    ["Iron Pickaxe"] = {
        Damage = 4,
        Durability = 300,
        SellValue = 75,
        Cost = {
            Wood = 5,
            Iron = 5,
        },
    };
}