return {
    ["Wooden Axe"] = {
        Luck = 3,
        HumanoidDamage = 6,
        Durability = 100,
        SellValue = nil,
        Cost = {
            Wood = 5,
        },
    };
    ["Wooden Pickaxe"] = {
        Luck = 3,
        HumanoidDamage = 6,
        Durability = 100,
        SellValue = nil,
        Cost = {
            Wood = 5,
        },
    };
    ["Stone Axe"] = {
        Luck = 2,
        HumanoidDamage = 10,
        Durability = 150,
        SellValue = 30,
        Cost = {
            Wood = 5,
            Stone = 5,
        },
    };
    ["Stone Pickaxe"] = {
        Luck = 2,
        HumanoidDamage = 10,
        Durability = 150,
        SellValue = 30,
        Cost = {
            Wood = 5,
            Stone = 5,
        },
    };
    ["Iron Axe"] = {
        Luck = 1,
        HumanoidDamage = 17,
        Durability = 300,
        SellValue = 75,
        Cost = {
            Wood = 5,
            Iron = 5,
        },
    };
    ["Iron Pickaxe"] = {
        Luck = 1,
        HumanoidDamage = 17,
        Durability = 300,
        SellValue = 75,
        Cost = {
            Wood = 5,
            Iron = 5,
        },
    };
}