return {
    ["Wooden Axe"] = {
        Layout = 1,
        Luck = 3,
        HumanoidDamage = 6,
        Durability = 100,
        BuyPrice = 5,
        SellPrice = nil,
        Cost = {
            Wood = 5,
        },
    };
    ["Wooden Pickaxe"] = {
        Layout = 2,
        Luck = 3,
        HumanoidDamage = 6,
        Durability = 100,
        BuyPrice = 5,
        SellPrice = nil,
        Cost = {
            Wood = 5,
        },
    };
    ["Stone Axe"] = {
        Layout = 5,
        Luck = 2,
        HumanoidDamage = 10,
        Durability = 150,
        BuyPrice = 40,
        SellPrice = 30,
        Cost = {
            Wood = 5,
            Stone = 5,
        },
    };
    ["Stone Pickaxe"] = {
        Layout = 6,
        Luck = 2,
        HumanoidDamage = 10,
        Durability = 150,
        BuyPrice = 40,
        SellPrice = 30,
        Cost = {
            Wood = 5,
            Stone = 5,
        },
    };
    ["Iron Axe"] = {
        Layout = 10,
        Luck = 1,
        HumanoidDamage = 17,
        Durability = 300,
        BuyPrice = 100,
        SellPrice = 75,
        Cost = {
            Wood = 5,
            Iron = 5,
        },
    };
    ["Iron Pickaxe"] = {
        Layout = 11,
        Luck = 1,
        HumanoidDamage = 17,
        Durability = 300,
        BuyPrice = 100,
        SellPrice = 75,
        Cost = {
            Wood = 5,
            Iron = 5,
        },
    };
}